# Lab 1: Introduction to R 

Please read the document [R-intro.pdf](https://cran.r-project.org/manuals.html). A good tutorial on R is available at [www3](https://www.w3schools.com/r/). In this lab, we will go through the following topics in R. 

- Getting help: google, manual, or ? 
- Numbers, vectors, and matrix, list 
- Math functions 
- String 
- Reading data from files 
- Generating random numbers 
- Loops  
- Writing your own functions 

## Installing R
Downloading R at https://cran.microsoft.com/ and following the instruction to install R on your computer. It is highly recommended to install RStudio available at https://posit.co/downloads/ and run R in RStudio. Alternatively, you may run R remotely at https://www.w3schools.com/r/r_intro.asp. 

## Getting help

- Google search "how to calculate average in R"
- Read the R manual
- Using ? in R

## Assignments 
We may use "=" or "<-" to assign values to variables. For example, we here generate a variable $x$ whose value is 3.

In [1]:
x <- 3 
x

[1] 3

We may generate a vector variable and use "[i]" to locate elements in the vector.

In [2]:
x <- 2:5 
x
x[2]

[1] 2 3 4 5

[1] 3

We may generate a string variable which is a vector of characters

In [3]:
x <- "I am a student" 
x
x[3]

[1] "I am a student"

[1] NA

We may generate a matrix variable and use "[i,j]" to locate elements in the vector.

In [4]:
x <- matrix(1:12, nrow=3, ncol=4)
x
x[1,2]
x[1,]
x[,2]

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[1] 4

[1]  1  4  7 10

[1] 4 5 6

A list variable may contain different types of data

In [5]:
x <- list() 
x[[1]] = "I am a student"
x[[2]] = 123
x

[[1]]
[1] "I am a student"

[[2]]
[1] 123

 

## Math functions

In [6]:
x=1:3
x*4 
exp(x) 
log(x) 
x=matrix(1,3,3) 
y=matrix(2,3,3) 
x%*%y 
x*y 

[1]  4  8 12

[1]  2.718282  7.389056 20.085537

[1] 0.0000000 0.6931472 1.0986123

[,1] [,2] [,3]
[1,] 6    6    6   
[2,] 6    6    6   
[3,] 6    6    6

[,1] [,2] [,3]
[1,] 2    2    2   
[2,] 2    2    2   
[3,] 2    2    2

## Functions for strings

In [7]:
x= rep("",3) 
x[1]  = "I am a graduate student"
x[2] = "who am I?" 
x[3] = "who are you?" 

nchar(x[1]) 
substring(x[1],1,3) 
strsplit(x[2], split=" ") 
paste("a","hello",sep="") 
grep("who",x) 
gsub("graduate","undergraduate",x) 
toupper(x) 
tolower(x)

[1] 23

[1] "I a"

[[1]]
[1] "who" "am"  "I?"

[1] "ahello"

[1] 2 3

[1] "I am a undergraduate student" "who am I?"                   
[3] "who are you?"

[1] "I AM A GRADUATE STUDENT" "WHO AM I?"              
[3] "WHO ARE YOU?"

[1] "i am a graduate student" "who am i?"              
[3] "who are you?"

 

## Reading data from files

In [8]:
data=read.csv("Lab 1 - data.csv") 
data
data[,1] = data[,1] * 10 
write.csv(data,"newdata.csv", row.names=F) 

V1         V2         V3         V4        
1  0.85332781 0.74786829 0.46077603 0.15329363
2  0.64914341 0.72662991 0.54947333 0.24407450
3  0.18542226 0.26383824 0.57954435 0.97183043
4  0.49988644 0.93933958 0.21200122 0.99106874
5  0.26374177 0.98626354 0.54450177 0.26758020
6  0.61112732 0.33217895 0.05834972 0.54131304
7  0.36914234 0.08085834 0.05588211 0.85876284
8  0.25350728 0.83706713 0.63014817 0.18264769
9  0.20357072 0.25849346 0.30214484 0.05598072
10 0.47116464 0.67394962 0.28081747 0.50700250
11 0.65012395 0.01026046 0.54948944 0.29967572
12 0.75223667 0.07775317 0.71929115 0.69480813
13 0.49442723 0.49138378 0.78043093 0.17591590
14 0.15364556 0.16670729 0.73303867 0.01809015
15 0.68046732 0.44405894 0.07383923 0.34538734
16 0.70716893 0.02882177 0.84202571 0.77440232
17 0.83129505 0.08661298 0.74557430 0.93672425
18 0.08638216 0.78741956 0.63246397 0.19764044
19 0.75538823 0.09585979 0.90368484 0.06294819
20 0.23711352 0.35896511 0.87965262 0.59115317
21 0.31184167 0.75218984 0.27041038 0.07943309
22 0.64790627 0.05523584 0.34259154 0.11879538
23 0.73803657 0.61349332 0.27953861 0.26276163
24 0.06645320 0.70710992 0.15588645 0.29456163
25 0.92541098 0.22925642 0.71822735 0.66264051

 
## Flow control

In [9]:
x=1 

y=2 

x==y 

x != y 

(x==1) || (y==2) 

(x==0) && (y==2) 

[1] FALSE

[1] TRUE

[1] TRUE

[1] FALSE

 

## Loops

In [10]:
x = runif(10, min=0, max=1) 
x
sum=0 
for(i in 1:10){
    sum=sum+x[i]
} 
sum 

[1] 0.6039337 0.7079896 0.9118515 0.4645942 0.7147664 0.6057385 0.7706831
 [8] 0.3512018 0.6703572 0.5368189

[1] 6.337935

In [11]:
x = 1:10
product = 1 
for(i in 1:10){
    product=product*x[i] 
}
product 

[1] 3628800

In [12]:
x = c(5,3,7,2)
n = length(x) 

for(i in 1:(n-1)){ 
    for(j in i:n){ 
        if(x[i]>x[j]){ 
            y=x[i] 
            x[i]=x[j] 
            x[j]=y 
        } 
    } 
} 
x

[1] 2 3 5 7

## Constructing your own functions 

my_function_name = function(x, y, ...){ 

…. 

return(result) 

}

In [13]:
my_sum = function(x){ 
    n = length(x)
    sum=0 
    for(i in 1:n){
        sum = sum + x[i] 
    } 
    sum 
}

x = 1:50
my_sum(x)

[1] 1275